### ISSUE TITLE
Problem when i try to install startbootstrap-sb-admin-2 with bower

### ISSUE THREAD

**Issue by jcarlosmr** [BlackrockDigital/startbootstrap-sb-admin-2#130]
I try to install startbootstrap-sb-admin-2 with bower but show me "bower ENORESTARGET  Tag/branch master does not exist" error and stop the installation

it was removed startbootstrap-sb-admin-2#3.3.7 branch from bower?

**Comment by jackboot7** [comment]
The error exists even old versions such as 1.0.7.

**Comment by gogus** [comment]
Temporary solution for that.
In your bower.json: 
` "startbootstrap-sb-admin-2": "https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git#master",`

**Comment by senoadiw** [comment]
Having same issue, locked to startbootstrap-sb-admin-2#1.0.8 and now getting this error:

bower ENORESTARGET  No tag found that was able to satisfy 1.0.8

**Comment by jcarlosmr** [comment]
Yes @senoadiw and, in fact that why i install the 3.3.7 update and it works fine the first time but two days later it failed.

But the solution posted by @jackboot7 works fine. Thank you!

**Comment by nelson6e65** [comment]
Why is happening this? :confused:

**Comment by nelson6e65** [comment]
```js
dependencies: {
    'startbootstrap-sb-admin-2': 'BlackrockDigital/startbootstrap-sb-admin-2#^3.3.7'
  }
```

**Comment by revbones** [comment]
Seems to still fail with that entry.

**Comment by davidtmiller** [comment]
I'm going to fix this up and get the repo re-registered with Bower and npm soon. Thanks for the updates.

**Comment by davidtmiller** [comment]
I will get this in, but it seems the Bower package was registered back when the organization was IronSummitMedia instead of BlackrockDigital. It looks like someone (somehow) went and made a user account called IronSummitMedia on GitHub and they created copycat repos. I was under the impression that it wasn't possible to take that username anymore since it was previously used on GitHub but it looks like someone took it and is planning to capitalize on it somehow. I've already submitted a trademark infringement request to GitHub and they are investigating. In the meantime I will get as much as I can cleaned up and pointing to the correct BlackrockDigital/sb-admin-2 repo instead of the old IronSummitMedia one (which is now a copycat).

And hopefully the old links floating around out there pointing to IronSummitMedia repos will get redirected once again at some point soon...

**Comment by star1609** [comment]
gogus please let us know in which json section should we add this varible "startbootstrap-sb-admin-2": "https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git#master",

**Comment by gogus** [comment]
@star1609:
`  "dependencies": {
    "startbootstrap-sb-admin-2": "https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git#master"
  }`

**Comment by davidtmiller** [comment]
Okay guys! No word yet from GitHub, but I am going to try to explain why Bower isn't working.

Earlier this year, the organization name IronSummitMedia was where all of the Start Bootstrap templates lived, including this one, was changed to BlackrockDigital. I informed that old links to the IronSummitMedia repositories would redirect to the new BlackrockDigital repositories, which they were for a while, until someone came along and created a user (not an organization) profile named ironsummitmedia.

This would be fine, except that this new imposter user who took the old organization name started created repositories to match the ones on Start Bootstrap, like sb-admin-2. The new repositories that got created seem to be some sort of spam, and I am not sure what the intentions were behind this, but I assume that the person who created the imposter account is trying to piggyback off of old backlinks to Start Bootstrap templates that are still floating around because now those old backlinks are redirecting to his imposter repositories.

The creation of this imposter ironsummitmedia user account created a bit of a ripple effect because the Bower Package for sb-admin-2 was set using that old account. Here's what I've done so far to try to fix this:
- First I tried to delete the existing startbootstrap-sb-admin-2 Bower Package from Bower but since the new ironsummitmedia imposter account holds the credentials I don't have access to delete the package (even though the package is still showing the star count and other information from the proper BlackrockDigital repository).
- I sent a trademark violation request to GitHub Support in an attempt to regain control of the IronSummitMedia profile name, so I can go and delete old Bower Packages (and other old packages in various other package managers) and create the new properly names packages using the BlackrockDigital repositories. I am waiting to hear back from GitHub still, but my hopes are high that the request will go through. Hopefully they will be able to give me temporary access to the account so I can go and delete any old packages, and then delete the account and make it unavailable and redirect everything to the BlackrockDigital repos like it was doing before.

That's currently where we stand with this. If I can't get a hold of GitHub or the imposter user then I will go ahead and create different Bower Packages and come up with a different naming convention for Start Bootstrap templates on Bower. For instance maybe something like `bower install sbootstrap-sb-admin-2` or something of that nature.

I'll keep everyone updated on my progress here. I've pushed a new update to the template as well today which takes the `bower_components` directory out of the base files and replaces it with a `vendor` directory instead which has only the distribution version of the vendor libraries that are dependencies for SB Admin 2. The new release also adds Gulp support if you want to develop on the themes CSS and JS on your own. It compiles the LESS and JS into minified versions and outputs it to the `dist` directory, and it includes a browserSync task for rapid development. This is more a build tool for me so I can make changes and updates to the style and functionality of the template quicker, which will be important moving into Bootstrap 4 development, but I'm sure there are some people out there who will want access to the source files in this nature.

Thanks for reading if you've made it this far. I will keep you updated on getting the Bower Package working again. Thanks everyone for your support!

**Comment by garak** [comment]
I'm looking for the content of the file that was previously found at `https://cdn.rawgit.com/IronSummitMedia/startbootstrap-sb-admin/gh-pages/css/sb-admin.css`
Where can I find it now?

**Comment by gogus** [comment]
@garak 
`https://cdn.rawgit.com/BlackrockDigital/startbootstrap-sb-admin-2/master/dist/css/sb-admin-2.css`

**Comment by garak** [comment]
@gogus that is the first one I tried, it looks like it's not the same file

**Comment by gogus** [comment]
Do you look for sb-admin or sb-admin-2?
You can find sb-admin at https://github.com/BlackrockDigital/startbootstrap-sb-admin

**Comment by garak** [comment]
@gogus thas was it! Thanks a lot :bow:

**Comment by jcarlosmr** [comment]
The solution for the moment is:



`bower.json:`

```
{
  "dependencies": {
    "startbootstrap-sb-admin-2": "BlackrockDigital/startbootstrap-sb-admin-2#^3.3.7"
  }
}
```
