### ISSUE TITLE
i would like to use this admin template in an open source project im developing

### ISSUE THREAD

**Issue by r3wt** [BlackrockDigital/startbootstrap-sb-admin-2#62]
i have a question about the apache license. how should i distribute the license. is it ok to just include a notice in a license file that the admin templates were built with startboostrap-sb-admin-2, and include there a copy of your license file as well as a link to the project/additional info?. 

the interface will be parted out into twig templates. having a license notice in every file seems like a pain in the ass. 

care to clarify?

**Comment by davidtmiller** [comment]
Don't worry about having a license notice on every file, as long as it's in the main project or something like that you should be fine, I want people to use this for whatever purpose!

**Comment by r3wt** [comment]
Thanks for the reply @davidtmiller I'm about to pull in a copy of the files in a few along with the license file. if its ok with you i would like you to review it and then confirm that i did the license correct.

**Comment by davidtmiller** [comment]
That looks good to me! Just a warning moving forward, in the coming month(s) I will be switching all of Start Bootstrap over to MIT (due to popular demand) so the license will change at some point. I am not going to come after anyone though who still has the Apache 2.0 License up there, but for what it's worth I wanted to let you know!
