### ISSUE TITLE
How to get a minified version for deployment?

### ISSUE THREAD

**Issue by sykano** [BlackrockDigital/startbootstrap-sb-admin-2#79]
This is probably wrong here, but I don't know where else to put it.
I don't quite get how to get or generate a minified version that can be used for deployment.
When I download the zip file or do "bower install ..." I get a lot of unnecessary stuff including examples and stuff from each package that I don't want to have lying around as assets. And a lot of the css and js aren't minified. Also, I don't need the source code versions of each package.
Is there a way to get a minified distribution?

**Comment by adriandmitroca** [comment]
You should use a build tool like Gulp or Grunt to handle all the required files (obviously - you won't need all SB Admin dependencies) so you concat all required styles and scripts using build tool and include one .css file and one .js file in your view template.

I highly recommend using Gulp because it's faster and more modern. Also I very like Laravel's approach to this subject - you can check it out at http://laravel.com/docs/5.1/elixir

**Comment by sykano** [comment]
Not what I have hoped for.
But thanks for the answer.

**Comment by davidtmiller** [comment]
@sykano I think that a build tool is a good option. All of the code in this template is purposely set up in an expanded format just for ease of use. Typically, a built tool like Grunt or Gulp will allow you to concat and minify your JS, so I would also recommend looking into those sorts of tools. The main idea with this template is to act as a baseline starting point for some sort of web app back-end, but it isn't really production ready out of the box, it's more of a boilerplate of sorts with a few cool features added into it to allow you to rapidly prototype something.

Hopefully this explains why things aren't minified by default, and gives some insight into how to get to your minified goals!

**Comment by rsjorslev** [comment]
Being an absolute beginner in terms of web front-end development i am trying to understand how i could use a build tool (Gulp) with sb-admin-2 as i would love to make a few simple change and have it setup so that i could use it on new projects really easily where it is more tailed towards what i would need.

Am i correct in understanding that i could setup gulp to do things like minify, compile less > css, create a dist folder for production purposes etc. but that none of this is included when i clone/fork sb-admin-2?

If that is correct i just need to figure out how to do that :) The laravel project seems to more or less do this but it is somewhat above my skill level to fully understand.

Thank you very much for building and maintaining this admin theme!

**Comment by davidtmiller** [comment]
I've now released some Gulp tasks that minify the compiled CSS and JS and throws them into the `dist` directory. You can use the minified versions of the CSS and JS directly from the `dist` or you can use the LESS files and the newly added Gulp tasks to further develop the theme as you wish!
